/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zbar_lib_ZbarManager */

#ifndef _Included_com_zbar_lib_ZbarManager
#define _Included_com_zbar_lib_ZbarManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zbar_lib_ZbarManager
 * Method:    decode
 * Signature: ([BIIZIIII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zbar_lib_ZbarManager_decode
  (JNIEnv *, jobject, jbyteArray, jint, jint, jboolean, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
